# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b84a032c547b2e27af7cbe60c17724f9ef08737d284f53b2db1d89bc1c1ba44ad44547f65d6cd451c94c98d0af35aec0d3d3a5b1e8d6c9cc2a494accad367e64

test:
  secret_key_base: 46df1f4ad8cbe34fda758539516e0b79fafcaf0a2fcce5fc3382ab6f420335fe19a376a6d986c6a45d1b6c21305eecc01bc9f35c39818db5afd265574102d591

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
